include:
  - proxy.yaml
services:
  db:
    image: mysql:latest
    restart: always
    networks:
      - backend
    environment: 
      - MYSQL_ROOT_PASSWORD=rootpass
      #- MYSQL_DATABASE=example
      #- MYSQL_USER=app
      #- MYSQL_PASSWORD=very_strong 
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
        #    ports:
        #- "3306:3306"
  web:
    build:
      context: .
      dockerfile: Docckerfile.python
    image: cr.yandex/crpqmq2ssc6b6lcodvpp/docker-2:latest
    restart: always
    entrypoint: ["./wait.sh"]
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"] 
    networks:
      backend:
        ipv4_address: 172.20.0.5
    depends_on: 
      - db
    ports:
      -  5000:5000
    environment:
      - DB_HOST=db
      - DB_USER=app  
      - DB_PASSWORD=very_strong
      - DB_NAME=example
      - DB_TABLE=webrequests
